version: '3'
services:
  jwt-fake-authorization-server:
    image: docker.local/jwt-fake-authorization-server:snapshot
    networks:
      - jwt-fake-authorization-server-network
    ports:
      - "9000:8080"
#    command: [
#        "java",
#        "org.springframework.boot.loader.JarLauncher"
#    ]


networks:
  jwt-fake-authorization-server-network: {}
